#!/usr/bin/perl
use strict;
use warnings;

sub take {
    my ($count) = @_;
    my $value = $_ & ((1<<$count)-1);
    $_ >>= $count;
    return $value;
}

sub b { $_[0] ? 1 : 0 }

sub main {
    print "// Auto-generated by abx_jumptable.pl\n";
    print "#define READRAM 0x1000\n";
    print "#define WRITERAM 0x1200\n";
    print "#define READHARD 0x1400\n";
    print "#define WRITEHARD 0x1600\n";
    print "#define NOP 0x1800\n";
    print "unsigned long jumptable[] = {\n    ";
    for my $key (0 .. 1023) {
        $_ = $key;
        my $hi5 = take(5) << 3;
        my $selftest = take(1);
        my $basic = take(1);
        my $osrom = take(1);
        my $rw = take(1);
        my $ref = take(1);

        my $selfrange = 0x50 <= $hi5 && $hi5 <= 0x57;
        my $basicrange = 0xa0 <= $hi5 && $hi5 <= 0xbf;
        my $hardrange = 0xd0 <= $hi5 && $hi5 <= 0xd7;
        my $osromrange = 0xc0 <= $hi5 && $hi5 <= 0xff;

        my $notram =
            $selfrange && $selftest ||
            $basicrange && $basic ||
            $hardrange ||
            $osromrange && $osrom;

        my $readram = !$notram && !$rw && !$ref;
        my $writeram = !$notram && $rw && !$ref;
        my $readhard = $hardrange && !$rw && !$ref;
        my $writehard = $hardrange && $rw && !$ref;

        use Data::Dumper;
        #print Dumper [map { $_, sprintf "%02x", eval "\$$_" } qw(selftest basic osrom hi5 rw ref)];

        my $label =
            $readram ? "READRAM" :
            $writeram ? "WRITERAM" :
            $readhard ? "READHARD" :
            $writehard ? "WRITEHARD" :
            "NOP";
        if ($key % 32 == 0) {
            print "// ref=$ref rw=$rw osrom=$osrom basic=$basic selftest=$selftest\n    ";
        }
        print $label;
        if (($key + 1) % 8) {
            print ", ";
        } elsif ($key == 1023) {
            print "\n";
        } else {
            print ",\n    ";
        }
    }
    print "};\n";
}

main();
